apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: o12qvuu63-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/o12qvuu63-java-springboot-gitops